name: CI for HelloWorld
 
 on:
  push:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version:3.8
    - name: Install Libraries
      run: |
        pip install flake8 pytest pytest-cov
    - name: Checkout own repo 
      uses: actions/checkout@v2
      with:
        repository: gerald-codes/pytest-test
    - name: Checkout Test Script
    uses: actions/checkout@v2
    with:
      repository: lowkh2/DevOpsQARepo
      path: tests
      token: ${{ secrets.QA_REMOTE_TEST }}
    - name: Begin PyTest
      run: |
        mv ./tests/*.* ./
        pytest --cov
