name: CI for HelloWorld
 
on:
 push:
   branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/setup-python@v2
       with:
         python-version: 3.8
     - name: Install Libraries
       run: |
         pip install flake8 pytest pytest-cov
     - name: Checkout own repo 
       uses: actions/checkout@v2
       with:
         repository: gerald-codes/pytest-test
     - name: Checkout Test Script
       uses: actions/checkout@v2
       with:
         repository: lowkh2/DevOpsQARepo
         path: tests
         token: ${{ secrets.QA_REMOTE }}
     - name: Linter Check with Flake8
       run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics 
     - name: Begin PyTest
       run: |
        mv ./tests/*.* ./
        pytest --cov -v --junitxml=report.xml
     - if: ${{failure()}}
       name: Create Issues
       uses: nashmaniac/create-issue-action@v1.1
       with:
           title: Build Failed
           token: ${{secrets.GITHUB.TOKEN}} 
           assigner: ${{github.actor}}
           labels: workflow-failed
           body: workflow failed for commit ${{github.sha}} @ ${{github.actor}}
     - name: publish Unit Test Results
       uses: EnricoMi/publish-unit-test-result-action@v1
       if: always()
       with:
           github_token: ${{secret.GITHUB_TOKEN}}
           file: report.xml
